modLoader = "lowcodefml"
loaderVersion = "[46,)"
license = "MIT"
issueTrackerURL="https://github.com/Team-Resourceful/Highlight/issues"

[[mods]]
modId = "highlight"
version = "${version}"
displayName = "Highlight"
authors = "ThatGravyBoat"
displayTest="IGNORE_ALL_VERSION"
description = '''
Highlight changes certain vanilla blocks from using ridgid selection/highlight shapes into have more defined ones with angles.
'''

[modproperties.highlight]
    'resourcefullib:resourcepack' = [
        { name="highlight_extended", description="Hightlight Extended" }
    ]

[[dependencies.highlight]]
    modId = "forge"
    mandatory = true
    versionRange = "[46,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.highlight]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.highlight]]
    modId = "resourcefullib"
    mandatory = true
    versionRange = "[1,)"
    ordering = "NONE"
    side = "BOTH"