modLoader = "lowcodefml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL="https://github.com/Team-Resourceful/Highlight/issues"

[[mods]]
    modId = "highlight"
    version = "${version}"
    displayName = "Highlight"
    authors = "ThatGravyBoat"
    displayTest="IGNORE_ALL_VERSION"
    description = '''
    Highlight changes certain vanilla blocks from using ridgid selection/highlight shapes into have more defined ones with angles.
    '''

[modproperties.highlight]
    'resourcefullib:resourcepack' = [
        { name="highlight_extended", description="Hightlight Extended" }
    ]

[[dependencies.highlight]]
    modId = "neoforge"
    type = "required"
    versionRange = "[20.5,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.highlight]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.20.5,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.highlight]]
    modId = "resourcefullib"
    type = "required"
    versionRange = "[1,)"
    ordering = "NONE"
    side = "BOTH"